"""Create rockets table

Revision ID: 71440eafea39
Revises: 
Create Date: 2025-02-03 12:13:42.675114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '71440eafea39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rockets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rocket_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('wikipedia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weight', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('cost_per_launch', sa.Integer(), nullable=True),
    sa.Column('first_flight', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stages', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rocket_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rockets')
    # ### end Alembic commands ###
