"""remove unused starlinks fields

Revision ID: 9245a2dd608e
Revises: 43c0813872aa
Create Date: 2025-02-06 17:33:24.079477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9245a2dd608e'
down_revision: Union[str, None] = '43c0813872aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('starlinks', 'object_name')
    op.drop_column('starlinks', 'country_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('starlinks', sa.Column('country_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('starlinks', sa.Column('object_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
