"""Create rocket and stages

Revision ID: a6dd1fffd3a4
Revises: 
Create Date: 2025-02-03 14:02:52.846341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a6dd1fffd3a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rockets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rocket_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('wikipedia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weight', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('cost_per_launch', sa.Integer(), nullable=True),
    sa.Column('first_flight', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stages', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rocket_uuid')
    )
    op.create_table('first_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reusable', sa.Boolean(), nullable=True),
    sa.Column('engines', sa.Integer(), nullable=True),
    sa.Column('fuel_amount_tons', sa.Integer(), nullable=True),
    sa.Column('burn_time_sec', sa.Integer(), nullable=True),
    sa.Column('rocket_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['rocket_uuid'], ['rockets.rocket_uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rocket_uuid')
    )
    op.create_table('second_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reusable', sa.Boolean(), nullable=True),
    sa.Column('engines', sa.Integer(), nullable=True),
    sa.Column('fuel_amount_tons', sa.Integer(), nullable=True),
    sa.Column('rocket_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['rocket_uuid'], ['rockets.rocket_uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rocket_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('second_stage')
    op.drop_table('first_stage')
    op.drop_table('rockets')
    # ### end Alembic commands ###
