"""Create launches table

Revision ID: baf67709171e
Revises: a6dd1fffd3a4
Create Date: 2025-02-03 14:14:56.037060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'baf67709171e'
down_revision: Union[str, None] = 'a6dd1fffd3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('launched_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upcoming', sa.Boolean(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('webcast', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('article', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rocket_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['rocket_uuid'], ['rockets.rocket_uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('launched_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('launches')
    # ### end Alembic commands ###
